apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus
    app.kubernetes.io/part-of: load-app-35138d8c-f696-463d-8a6b-48f89b8e1354
  name: devfile-sample-code-with-vvpl
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-code-with-quarkus
    weight: null
status: {}
